### ISSUE TITLE
Dependency on form-data

### ISSUE THREAD

**Issue by dfjimenezt** [thencc/gpt-ts#1]
When init the GPTs there is a external dependency on form-data 

![image](https://user-images.githubusercontent.com/9205358/117842892-f6e9c300-b243-11eb-9498-4d4647f58084.png)

![image](https://user-images.githubusercontent.com/9205358/117843111-28628e80-b244-11eb-8ebe-2c10991fa7c7.png)

In order to fix just install form-data and works properly

`npm i form-data`

**Comment by spencercap** [comment]
@dfjimenezt 
glad to hear you were able to resolve this on your own! 

which version of `gpts` were you using though? i hit this snag a couple months ago as well and upgraded the library to use `axios` instead of `node-fetch` and `form-data` was added as dependency too
